name: Lint-Format-Scan
on: [push]
jobs:
  terraform_fmt:
    name: Run terraform fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: setup
        run: |
          apt update
          apt install -y curl unzip software-properties-common python3 python3-pip python-is-python3
          apt-get install --reinstall xdg-utils
          python3 -m pip install --upgrade pip
          pip3 install --no-cache-dir pre-commit
          pip3 install --no-cache-dir checkov
          curl -L "$(curl -s https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest | grep -o -E -m 1 "https://.+?-linux-amd64.tar.gz")" > terraform-docs.tgz && tar -xzf terraform-docs.tgz terraform-docs && rm terraform-docs.tgz && chmod +x terraform-docs && mv terraform-docs /usr/bin/
          curl -L "$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E -m 1 "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz && tar -xzf terrascan.tar.gz terrascan && rm terrascan.tar.gz &&  mv terrascan /usr/bin/ && terrascan init
          curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E -m 1 "https://.+?_linux_amd64.zip")" > tflint.zip && unzip tflint.zip && rm tflint.zip &&  mv tflint /usr/bin/
          curl -L "$(curl -s https://api.github.com/repos/aquasecurity/tfsec/releases/latest | grep -o -E -m 1 "https://.+?tfsec-linux-amd64")" > tfsec && chmod +x tfsec &&  mv tfsec /usr/bin/
          curl -L "$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep -o -E -i -m 1 "https://.+?/trivy_.+?_Linux-64bit.tar.gz")" > trivy.tar.gz && tar -xzf trivy.tar.gz trivy && rm trivy.tar.gz &&  mv trivy /usr/bin
          apt install -y jq && \
          curl -L "$(curl -s https://api.github.com/repos/minamijoyo/tfupdate/releases/latest | grep -o -E -m 1 "https://.+?_linux_amd64.tar.gz")" > tfupdate.tar.gz && tar -xzf tfupdate.tar.gz tfupdate && rm tfupdate.tar.gz &&  mv tfupdate /usr/bin/
          curl -L "$(curl -s https://api.github.com/repos/minamijoyo/hcledit/releases/latest | grep -o -E -m 1 "https://.+?_linux_amd64.tar.gz")" > hcledit.tar.gz && tar -xzf hcledit.tar.gz hcledit && rm hcledit.tar.gz &&  mv hcledit /usr/bin/
      - name: Terraform fmt
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: terraform_fmt --all-files
  terraform_lint:
    name: Run tflint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install tflint
        uses: nick-fields/retry@v3.0.1
        with:
          timeout_seconds: 30
          max_attempts: 5
          retry_on: error
          command: >-
            curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: terraform_tflint --all-files
  terraform_trivy:
    name: Run trivy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install trivy
        uses: nick-fields/retry@v3.0.1
        with:
          timeout_seconds: 60
          max_attempts: 5
          retry_wait_seconds: 20
          retry_on: error
          command: |
            apt-get install wget apt-transport-https gnupg lsb-release
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
            echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
            sudo apt-get update
            sudo apt-get install trivy
            trivy version
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: terraform_trivy --all-files
  terraform_validate:
    name: Run terraform validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: setup
        run: |
          apt update
          apt install -y curl unzip software-properties-common python3 python3-pip python-is-python3
          apt-get install --reinstall xdg-utils
          python3 -m pip install --upgrade pip
          pip3 install --no-cache-dir pre-commit
          pip3 install --no-cache-dir checkov
          curl -L "$(curl -s https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest | grep -o -E -m 1 "https://.+?-linux-amd64.tar.gz")" > terraform-docs.tgz && tar -xzf terraform-docs.tgz terraform-docs && rm terraform-docs.tgz && chmod +x terraform-docs &&  mv terraform-docs /usr/bin/
          curl -L "$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E -m 1 "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz && tar -xzf terrascan.tar.gz terrascan && rm terrascan.tar.gz &&  mv terrascan /usr/bin/ && terrascan init
          curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E -m 1 "https://.+?_linux_amd64.zip")" > tflint.zip && unzip tflint.zip && rm tflint.zip &&  mv tflint /usr/bin/
          curl -L "$(curl -s https://api.github.com/repos/aquasecurity/tfsec/releases/latest | grep -o -E -m 1 "https://.+?tfsec-linux-amd64")" > tfsec && chmod +x tfsec &&  mv tfsec /usr/bin/
          curl -L "$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep -o -E -i -m 1 "https://.+?/trivy_.+?_Linux-64bit.tar.gz")" > trivy.tar.gz && tar -xzf trivy.tar.gz trivy && rm trivy.tar.gz &&  mv trivy /usr/bin
          apt install -y jq && \
          curl -L "$(curl -s https://api.github.com/repos/minamijoyo/tfupdate/releases/latest | grep -o -E -m 1 "https://.+?_linux_amd64.tar.gz")" > tfupdate.tar.gz && tar -xzf tfupdate.tar.gz tfupdate && rm tfupdate.tar.gz &&  mv tfupdate /usr/bin/
          curl -L "$(curl -s https://api.github.com/repos/minamijoyo/hcledit/releases/latest | grep -o -E -m 1 "https://.+?_linux_amd64.tar.gz")" > hcledit.tar.gz && tar -xzf hcledit.tar.gz hcledit && rm hcledit.tar.gz &&  mv hcledit /usr/bin/
      - name: Generate pvt key
        run: >-
          ssh-keygen -q -P '' -t rsa -b 4096 -m PEM -f tests/domino.pem
      - name: Terraform validate
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: terraform_validate --all-files
  terraform_providers_lock:
    name: Run terraform providers_lock
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Generate pvt key
        run: ssh-keygen -q -P '' -t rsa -b 4096 -m PEM -f tests/domino.pem
      - name: Terraform providers_lock
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: terraform_providers_lock --all-files
  terraform_docs:
    name: Run terraform docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install terraform docs
        uses: nick-fields/retry@v3.0.1
        with:
          timeout_seconds: 60
          max_attempts: 5
          retry_wait_seconds: 20
          retry_on: error
          command: >-
            curl -L https://github.com/terraform-docs/terraform-docs/releases/download/v0.19.0/terraform-docs-v0.19.0-linux-amd64.tar.gz | tar -C /tmp -xzf - && chmod +x /tmp/terraform-docs &&  mv /tmp/terraform-docs /usr/local/bin
      - name: Terraform docs
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: terraform_docs --all-files
  checkov:
    name: Run checkov scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v5
      - name: Install checkov
        run: pip3 install checkov
      - name: Run Checkov scan
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: terraform_checkov --all-files
  check_aws_partition:
    name: Check for hardcoded aws partition
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check for hardcoded aws partition
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: check_aws_partition --all-files
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        id: test
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.2.0
        env:
          CCI_TOKEN: ${{ secrets.CIRCLE_PERSONAL_TOKEN }}
